name: Maven CI/CD

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: zulu
          java-package: jdk+fx
          architecture: x64
          cache: maven

      - name: Maven bump version
        run: ./mvnw -B build-helper:parse-version versions:set -DnewVersion=\\${parsedVersion.majorVersion}.\\${parsedVersion.minorVersion}.\\${parsedVersion.incrementalVersion}
      - name: Maven build
        run: ./mvnw -B clean package

