name: Maven CI/CD

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: zulu
          java-package: jdk+fx
          architecture: x64
          cache: maven

      - name: Maven bump version
        run: ./mvnw -B build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'
      - name: Maven build
        run: ./mvnw -B clean package
      - name: Maven next version
        run: ./mvnw -B build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'
      - name: Commit version
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Christophe
          author_email: ouaibsky@gmail.com
          message: 'Next Version [skip ci]'
          add: 'pom.xml'
